on:
  push:
    branches: [ main ]
env:
  api_url: ${{ vars.VITE_API_URL }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo API URL
        run: |
          echo "repository variable : $api_url"
          echo "repository variable : $api_url"
      - name: create env file
        run: |
          touch .env
          echo "VITE_API_URL=$api_url" >> .env
          cat .env
      - name: Build
        run: yarn install && yarn build
      - name: Publish
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: quest-app
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
